#!/usr/bin/env python3
"""Export SQLite database to SQL statements for Cloudflare D1 import.

Usage:
  python3 export-to-d1.py

Generates d1-organizations.sql, d1-volunteer_opportunities.sql, d1-stays.sql, d1-events.sql
Then import each with:
  npx wrangler d1 execute volunteer-map-db --remote --file=d1-organizations.sql
"""
import sqlite3
import os

DB_PATH = "/home/user/volunteer-map/backend/organizations.db"
OUT_DIR = "/home/user/volunteer-map"

# D1 schema columns (must match schema.sql)
D1_COLUMNS = {
    'organizations': [
        'id', 'name', 'description', 'organization_type', 'popup_html', 'website',
        'email', 'phone', 'address', 'city', 'region', 'country', 'postal_code',
        'latitude', 'longitude', 'location', 'source', 'accepts_volunteers',
        'accepts_visitors', 'accepts_shortterm', 'accepts_longterm', 'has_jobs',
        'has_stays', 'has_events', 'last_updated', 'created_at',
        'directory_url', 'direct_website', 'last_scrape_attempt',
        'being_processed_since', 'events_scraped_at', 'jobs_rescraped',
        'jobs_being_processed_since'
    ],
    'volunteer_opportunities': [
        'id', 'organization_id', 'title', 'description', 'role', 'skills_needed',
        'start_date', 'end_date', 'commitment', 'remote_options',
        'application_email', 'source_url', 'created_at'
    ],
    'stays': [
        'id', 'organization_id', 'title', 'description', 'stay_type', 'price_info',
        'booking_type', 'booking_analysis', 'booking_url', 'created_at'
    ],
    'events': [
        'id', 'organization_id', 'title', 'description', 'event_type',
        'start_date', 'end_date', 'location', 'is_online', 'is_in_person',
        'registration_url', 'event_url', 'created_at'
    ],
}

def escape_sql(val):
    if val is None:
        return 'NULL'
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, str):
        return "'" + val.replace("'", "''") + "'"
    return 'NULL'

def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    for table, cols in D1_COLUMNS.items():
        col_list = ', '.join(cols)
        rows = conn.execute(f'SELECT {col_list} FROM {table}').fetchall()

        outpath = os.path.join(OUT_DIR, f'd1-{table}.sql')
        with open(outpath, 'w', encoding='utf-8') as f:
            f.write(f'-- {table}: {len(rows)} rows\n')

            if table == 'organizations':
                # Use upserts for organizations so user submissions (source='user_submitted') in D1 are preserved
                # and updated from SQLite on conflict.
                f.write(f'-- Upserting organizations (preserves user submissions in D1)\n')
                updates = ', '.join(f'{col}=excluded.{col}' for col in cols if col != 'id')
                for row in rows:
                    values = ', '.join(escape_sql(row[col]) for col in cols)
                    f.write(f'INSERT INTO {table} ({col_list}) VALUES ({values}) ON CONFLICT(id) DO UPDATE SET {updates};\n')
            else:
                # Events, jobs, stays are fully regenerated by scrapers.
                f.write(f'DELETE FROM {table};\n')
                for row in rows:
                    values = ', '.join(escape_sql(row[col]) for col in cols)
                    f.write(f'INSERT INTO {table} ({col_list}) VALUES ({values});\n')
            f.write('\n')
        print(f'Wrote {len(rows)} rows to {outpath}')

    conn.close()
    print('Done')

if __name__ == '__main__':
    main()
